# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "beautifulsoup4",
#     "cloudscraper",
#     "requests",
# ]
# ///
"""Generate RSS feeds for sites that don't publish one.

Reads `rss_hub/sources.json`, dispatches to a per-site adapter, and writes an
RSS 2.0 feed per source under `rss_hub/output/<slug>.xml`. The feed.xml files
are deployed by `deploy-pages.yml` to `https://tools.paul-learning.dev/rss_hub/`.
"""

from __future__ import annotations

import json
import sys
import time
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from email.utils import format_datetime
from pathlib import Path

import requests

try:
    import cloudscraper  # type: ignore
except ImportError:  # pragma: no cover - script env always has it
    cloudscraper = None

BASE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(BASE_DIR))

from adapters import get_adapter  # noqa: E402
from adapters.hackmd import slug_from_url  # noqa: E402

SOURCES_PATH = BASE_DIR / "sources.json"
OUTPUT_DIR = BASE_DIR / "output"
PUBLIC_BASE = "https://tools.paul-learning.dev/rss_hub"
DEFAULT_MAX_ITEMS = 50
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15"
)


def log(msg: str) -> None:
    print(msg, flush=True)


def fetch_html(url: str) -> str:
    headers = {
        "User-Agent": USER_AGENT,
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9,zh-TW;q=0.8",
    }
    last_exc: Exception | None = None
    for attempt in range(3):
        try:
            resp = requests.get(url, headers=headers, timeout=30)
            if resp.status_code == 200:
                return resp.text
            if resp.status_code in (403, 503) and cloudscraper is not None:
                scraper = cloudscraper.create_scraper()
                resp = scraper.get(url, headers=headers, timeout=30)
                if resp.status_code == 200:
                    return resp.text
            resp.raise_for_status()
            return resp.text
        except requests.RequestException as exc:
            last_exc = exc
            time.sleep(2 ** attempt)
    raise RuntimeError(f"failed to fetch {url}: {last_exc}")


def build_feed(*, title: str, source_url: str, public_link: str, items) -> bytes:
    rss = ET.Element("rss", {"version": "2.0", "xmlns:atom": "http://www.w3.org/2005/Atom"})
    channel = ET.SubElement(rss, "channel")
    ET.SubElement(channel, "title").text = title
    ET.SubElement(channel, "link").text = source_url
    ET.SubElement(
        channel,
        "atom:link",
        {"href": public_link, "rel": "self", "type": "application/rss+xml"},
    )
    ET.SubElement(channel, "description").text = f"Generated by rss_hub from {source_url}"
    ET.SubElement(channel, "lastBuildDate").text = format_datetime(
        datetime.now(tz=timezone.utc)
    )

    for item in items:
        node = ET.SubElement(channel, "item")
        ET.SubElement(node, "title").text = item.title
        ET.SubElement(node, "link").text = item.link
        ET.SubElement(node, "guid", {"isPermaLink": "true"}).text = item.guid
        if item.pub_date is not None:
            ET.SubElement(node, "pubDate").text = format_datetime(item.pub_date)

    ET.indent(rss, space="", level=0)
    return b'<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(rss, encoding="utf-8")


def process_source(source: dict) -> bool:
    url = source["url"]
    title = source.get("title") or url
    max_items = int(source.get("max_items", DEFAULT_MAX_ITEMS))

    adapter = get_adapter(url)
    log(f"[{url}] fetching via {adapter.__name__}")
    items = adapter.fetch_items(url, fetcher=fetch_html)
    if not items:
        log(f"[{url}] WARN: adapter returned 0 items; keeping existing feed if any")
        return False

    items = items[:max_items]

    slug = slug_from_url(url)
    out_path = OUTPUT_DIR / f"{slug}.xml"
    public_link = f"{PUBLIC_BASE}/{slug}.xml"
    payload = build_feed(
        title=title,
        source_url=url,
        public_link=public_link,
        items=items,
    )
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(payload)
    log(f"[{url}] wrote {out_path} with {len(items)} items")
    return True


def main() -> int:
    if not SOURCES_PATH.exists():
        log(f"no sources file at {SOURCES_PATH}")
        return 0
    sources = json.loads(SOURCES_PATH.read_text(encoding="utf-8"))
    failures = 0
    for source in sources:
        try:
            process_source(source)
        except Exception as exc:  # noqa: BLE001 - keep going on per-source errors
            failures += 1
            log(f"[{source.get('url')}] ERROR: {exc}")
    return 1 if failures and failures == len(sources) else 0


if __name__ == "__main__":
    sys.exit(main())
